{{- if and .Values.linkerd.inject .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include "hello-dotnet.fullname" . }}l5d-header-middleware"
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "{{ include "hello-dotnet.fullname" . }}-http.{{ .Release.Namespace }}.svc.cluster.local:8080"
{{- end }}