{{- if .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "hello-dotnet.fullname" . }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  entryPoints:
    {{- range .Values.traefik.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
  - match: Host(`{{ .Values.url }}`) && (PathPrefix(`/hello`) || PathPrefix(`/calldown`))
    kind: Rule
    {{- if and .Values.linkerd.inject }}
    middlewares:
    - name: "{{ include "hello-dotnet.fullname" . }}l5d-header-middleware"
    {{- end }}
    services:
    - name: {{ include "hello-dotnet.fullname" . }}-http
      port: 8080
  {{- if .Values.traefik.tls.certResolver }}
  tls:
    certResolver: {{ .Values.traefik.tls.certResolver }}
  {{- end}}
{{- end }}