# Default values for hello-go-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/tjololo/hello-go-web
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.1.0"

url: dev.418.cloud

labels: {}

linkerd:
  inject: true

keda:
  scale: false
  threshold: 10
  min: 0
  max: 10
  cooldown: 300

# Expose the service externally with contour.
contour:
  enabled: false

# Expose the service externally with traefik.
traefik:
  enabled: false
  entryPoints:
    - websecure
  # tls:
  #   secretName: my-secret-cert
  #   domains:
  #     main: example.com

hpa:
  enabled: false
  replicas:
    min: 2
    max: 10
  avgCpuUtilization: 70
  behavior:
    stabilizationWindowSeconds:
      scaleUp: 0
      scaleDown: 120

flagger:
  enabled: false