  
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hello-go-web.fullname" . }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hello-go-web.fullname" . }}
  minReplicas: {{ .Values.hpa.replicas.min | default 2 }}
  maxReplicas: {{ .Values.hpa.replicas.max | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.avgCpuUtilization | default 70}}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.stabilizationWindowSeconds.scaleDown | default 120 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.stabilizationWindowSeconds.scaleUp | default 0 }}
{{- end }}