{{- if .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "hello-go-web.fullname" . }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  entryPoints:
    {{- range .Values.traefik.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
  - match: Host(`{{ .Values.url }}`) && PathPrefix(`/hello`)
    kind: Rule
    services:
    {{- if .Values.flagger.enabled }}
    - name: {{ include "hello-go-web.fullname" . }}
      port: 8080
    {{- else }}
    - name: {{ include "hello-go-web.fullname" . }}-http
      port: 8080
    {{- end }}
  tls:
    certResolver: {{ .Values.traefik.tls.certResolver }}
{{- end }}